/*
 * Generated by ISE 22.12.10.6463 - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F235_6594();
extern void F237_6770();
extern void F235_6598();
extern void F242_6838();
extern void F243_6979();
extern void F242_6843();
extern void F275_3176();
extern void F263_6475();
extern void F61_1346();
extern EIF_REFERENCE F61_1333();
extern EIF_BOOLEAN F61_1345();
extern EIF_BOOLEAN F61_1353();
extern void F61_1355();
extern void F61_1356();
extern void F61_1357();
extern void F54_1259();
extern EIF_TYPED_VALUE F54_1260();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F235_6594;
	egc_immstr8make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F235_6598;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F242_6838;
	egc_immstr32make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F242_6843;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F275_3176;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F237_6770;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F243_6979;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F263_6475;
	egc_is_scoop_capable = 1;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F61_1346;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F61_1345;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F61_1333;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F61_1353;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F61_1355;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F61_1356;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F61_1357;

	egc_str_dtype = 236;

	egc_immstr8_dtype = 245;

	egc_str32_dtype = 242;

	egc_immstr32_dtype = 244;
	egc_arr_dtype = 274;
	egc_tup_dtype = 190;
	egc_disp_rout_id = 3107;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x0355;
	egc_sp_wchar = 0x021F;
	egc_sp_bool = 0x01C9;
	egc_sp_uint8 = 0x0279;
	egc_sp_uint16 = 0x023C;
	egc_sp_uint32 = 0x0181;
	egc_sp_uint64 = 0x02C5;
	egc_sp_int8 = 0x030D;
	egc_sp_int16 = 0x0331;
	egc_sp_int32 = 0x0150;
	egc_sp_int64 = 0x02E9;
	egc_sp_real32 = 0x02A1;
	egc_sp_real64 = 0x01A5;
	egc_sp_pointer = 0x01EB;
	egc_sp_ref = 0x0108;

	egc_uint8_dtype = 213;
	egc_uint16_dtype = 219;
	egc_uint32_dtype = 216;
	egc_uint64_dtype = 228;
	egc_int8_dtype = 192;
	egc_int16_dtype = 225;
	egc_int32_dtype = 222;
	egc_int64_dtype = 204;
	egc_bool_dtype = 207;
	egc_real32_dtype = 195;
	egc_char_dtype = 201;
	egc_wchar_dtype = 198;
	egc_real64_dtype = 210;
	egc_point_dtype = 231;

	egc_exception_dtype = 72;
	egc_except_emnger_dtype = 60;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "project";
	egc_system_location = "C:\\Users\\ArminC\\Documents\\Eiffel User Files\\22.12\\projects\\project\\EIFGENs\\project\\W_code";
	egc_compiler_tag = 39;
	egc_project_version = 1682666510;
	egc_has_old_special_semantic = 0;
	scount = 1047;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 5165;
	egc_rcarg[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	egc_rcrid[1] = 5698;
	egc_rcarg[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	egc_rcrid[2] = 6128;
	egc_rcarg[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 53;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F54_1259;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F54_1260;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 974; /* APPLICATION */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 1020; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 1044; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
